var http = require('http');
var formidable = require('formidable');
var fs = require('fs');
var util = require('util');

http.createServer(function (req, res) {
  if (req.url == '/fileupload') {
    var form = new formidable.IncomingForm();
    form.parse(req, function (err, fields, files) {
      var oldpath = files.filetoupload.path;
      var newpath = '/media/Upload/' + files.filetoupload.name;
      var readStream = fs.createReadStream(files.filetoupload.path);
      var writeStream = fs.createWriteStream("/media/Upload/" + String(files.filetoupload.name));
       
      readStream.pipe(writeStream);
      res.write( '<!DOCTYPE html>\n' );
      res.write( '<html>\n' );
      res.write( '<head>\n' );
      res.write( '    <meta charset=\"utf-8\">\n' );
      res.write( '	<title>Upload</title>\n' );
      res.write( '</head>\n' );
      res.write( '\n' );
      res.write( '<body>\n' );
      res.write( '    <style>  \n' );
      res.write( '        body {\n' );
      res.write( '            background-color:rgb(22, 22, 22);\n' );
      res.write( '            height:100%;\n' );
      res.write( '        }\n' );
      res.write( '        .text{\n' );
      res.write( '            position: relative;\n' );
      res.write( '            font-size: 25px;\n' );
      res.write( '            color: ghostwhite;\n' );
      res.write( '            z-index: 10;\n' );
      res.write( '            font-weight: bold;\n' );
      res.write( '            display:flex;\n' );
      res.write( '            justify-content:center;\n' );
      res.write( '            align-items: center;\n' );
      res.write( '            height:200px;\n' );
      res.write( '            vertical-align: middle;\n' );
      res.write( '        }\n' );
      res.write( '        .form-submit-button { \n' );
      res.write( '            position: absolute;\n' );
      res.write( '            background: rgb(41, 41, 41 );\n' );
      res.write( '            color: #fff; \n' );
      res.write( '            border: 1px solid #eee; \n' );
      res.write( '            border-radius: 20px; \n' );
      res.write( '            font-weight: bold; \n' );
      res.write( '            font-size: 20px; \n' );
      res.write( '            text-shadow:none; \n' );
      res.write( '            width: 130px; \n' );
      res.write( '            height: 60px; \n' );
      res.write( '        } \n' );
      res.write( '        .form-submit-button:hover { \n' );
      res.write( '            background: #339A62; \n' );
      res.write( '            color: #fff; \n' );
      res.write( '            border: 1px solid #eee; \n' );
      res.write( '            border-radius: 20px; \n' );
      res.write( '            text-shadow:none; \n' );
      res.write( '        } \n' );
      res.write( '        </style>\n' );
      res.write( '    <body>\n' );
      res.write( '        <div class=\"text\">Upload Finish</div>\n' );
      res.write( '        <button class=\"form-submit-button\" style=\"right: 60%\" onclick=\"location.href=\'http://192.168.211.1\'\">\n' );
      res.write( '            Playback\n' );
      res.write( '        </button>\n' );
      res.write( '        <button class=\"form-submit-button\" style=\"left: 60%\" onclick=\"location.href=\'http://192.168.211.1:8080\'\">\n' );
      res.write( '            Upload\n' );
      res.write( '        </button>\n' );
      res.write( '    </body>\n' );
      res.write( '\n' );
      res.write( '\n' );
      res.write( '    <script src=\"jquery-ui-1.12.1.custom/external/jquery/jquery.js\"></script>\n' );
      res.write( '    <script src=\"jquery-ui-1.12.1.custom/jquery-ui.js\"></script>\n' );
      res.write( '    \n' );
      res.write( '</body>\n' );
      res.write( '\n' );
      res.write( '</html>\n' );
      
        res.end();
 });
  } else {
    res.writeHead(200, {'Content-Type': 'text/html'});
    res.write( '<!DOCTYPE html>' );
    res.write( '<head>\n' );
    res.write( '	<meta charset=\"utf-8\">\n' );
    res.write( '	<title>Upload</title>\n' );
    res.write( '</head>' );
    res.write( '<style>\n' );
    res.write( '  html{\n' );
    res.write( '    height:100%;\n' );
    res.write( '  }\n' );
    res.write( '  \n' );
    res.write( '  body{\n' );
    res.write( '    \n' );
    res.write( '    background-color:rgb(22, 22, 22);\n' );
    res.write( '    height:100%;\n' );
    res.write( '  }\n' );
    res.write( '  \n' );
    res.write( '  .wrapper{\n' );
    res.write( '    \n' );
    res.write( '    width:100%;\n' );
    res.write( '    height:100%;\n' );
    res.write( '    display:flex;\n' );
    res.write( '    align-items:center;\n' );
    res.write( '    justify-content:center;\n' );
    res.write( '  }\n' );
    res.write( '  \n' );
    res.write( '    .file-upload{\n' );
    res.write( '  \n' );
    res.write( '      height:200px;\n' );
    res.write( '      width:200px;\n' );
    res.write( '      border-radius: 100px;\n' );
    res.write( '      position:relative;\n' );
    res.write( '      \n' );
    res.write( '      display:flex;\n' );
    res.write( '      justify-content:center;\n' );
    res.write( '      align-items: center;  \n' );
    res.write( '  \n' );
    res.write( '      border:4px solid #FFFFFF;\n' );
    res.write( '      overflow:hidden;\n' );
    res.write( '      background-image: linear-gradient(to bottom, rgb(59, 59, 59) 50%, #FFFFFF 50%);\n' );
    res.write( '      background-size: 100% 200%;\n' );
    res.write( '      transition: all 1s;\n' );
    res.write( '      color: #FFFFFF;\n' );
    res.write( '      font-size:100px;\n' );
    res.write( '    }\n' );
    res.write( '  \n' );
    res.write( '      input[type=\'file\']{\n' );
    res.write( '  \n' );
    res.write( '        height:200px;\n' );
    res.write( '        width:200px;\n' );
    res.write( '        position:absolute;\n' );
    res.write( '        top:0;\n' );
    res.write( '        left:0;\n' );
    res.write( '        opacity:0;\n' );
    res.write( '        cursor:pointer;\n' );
    res.write( '  \n' );
    res.write( '      }\n' );
    res.write( '  \n' );
    res.write( '      .file-upload:hover{\n' );
    res.write( '  \n' );
    res.write( '      background-image: linear-gradient(to bottom, rgb(100, 100, 100) 50%, #FFFFFF 50%);\n' );
    res.write( '        color:#339A62\n' );
    res.write( '  \n' );
    res.write( '      }\n' );
    res.write( '      .form-submit-button {\n' );
    res.write( '        background: rgb(41, 41, 41);\n' );
    res.write( '        color: #fff;\n' );
    res.write( '        border: 1px solid #eee;\n' );
    res.write( '        border-radius: 20px;\n' );
    res.write( '        font-weight: bold;\n' );
    res.write( '        font-size: 20px;\n' );
    res.write( '        text-shadow:none;\n' );
    res.write( '        width: 200px;\n' );
    res.write( '        height: 100px;\n' );
    res.write( '        visibility: hidden;\n' );
    res.write( '      }\n' );
    res.write( '      .form-submit-button:hover {\n' );
    res.write( '        background: #339A62;\n' );
    res.write( '        color: #fff;\n' );
    res.write( '        border: 1px solid #eee;\n' );
    res.write( '        border-radius: 20px;\n' );
    res.write( '        text-shadow:none;\n' );
    res.write( '      }\n' );
    res.write( '      .text {\n' );
    res.write( '        z-index: 10;\n' );
    res.write( '        font-size: 25px;\n' );
    res.write( '        color:ghostwhite;\n' );
    res.write( '        font-weight: bold;\n' );
    res.write( '        text-align:left;\n' )
    res.write( '      }\n' );
    res.write( '  </style>\n' );
    res.write( '  <body>\n' );
    res.write( '    <div class=\"wrapper\">\n' );
    res.write( '          <form action=\"fileupload\" method=\"post\" enctype=\"multipart/form-data\">\n' );
    res.write( '            <div class=\"file-upload\"> \n' );
    res.write( '                <input type=\"file\" id=\"real-file\" name=\"filetoupload\"><br>\n' );
    res.write( '                <img src=\"http://192.168.211.1/arrow_up.png\" style=\"width = 50px; height = 50px \">' );
    res.write( '              </div><br>\n' );
    res.write( '              <div id=\"custom-text\" class=\"text\">No file chosen</div><br>\n' );
    res.write( '        <input type=\"submit\" id=\"custom-button\" value=\"Upload\" class=\"form-submit-button\">\n' );
    res.write( '          </form>\n' );
    res.write( '    </div>\n' );
    res.write( '  </body>\n' );
    res.write( '  <script>\n' );
    res.write( '      const realFileBtn = document.getElementById(\"real-file\");\n' );
    res.write( '      const customBtn = document.getElementById(\"custom-button\");\n' );
    res.write( '      const customTxt = document.getElementById(\"custom-text\");\n' );
    res.write( '\n' );
    res.write( '      realFileBtn.addEventListener(\"change\", function() {\n' );
    res.write( '        if (realFileBtn.value) {\n' );
    res.write( '          var str = String(realFileBtn.value);\n' );
    res.write( '          var split = str.split(\'\\\\\');\n' );
    res.write( '          console.log(str);\n  ');
    res.write( '          console.log(String(split));\n  ');
    res.write( '          customTxt.innerHTML = String(split[split.length - 1]);\n' );
    res.write( '          document.getElementById(\"custom-button\").style.visibility = \"visible\";    \n' );
    res.write( '        } else {\n' );
    res.write( '          customTxt.innerHTML = \"No file chosen, yet.\";\n' );
    res.write( '        }\n' );
    res.write( '      });\n' );
    res.write( '  </script>' );
    res.write( '    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.8.1/css/all.css\" integrity=\"sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf\" crossorigin=\"anonymous\">\n' );
    res.write( '    <link rel="stylesheet" href="./font-awesome.min.css">\n' );
    res.write( '</html>' );
    
    return res.end();
  }
}).listen(8080); 